name = "DistanceTransforms"
uuid = "71182807-4d06-4237-8dd0-bdafe4d097e2"
authors = ["Dale <djblack@uci.edu> and contributors"]
version = "0.1.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
FLoops = "cc61a311-1640-44b5-9fba-1b764f453329"
FoldsCUDA = "6cd66ae4-5932-4b96-926d-e73e578e42cc"
ImageMorphology = "787d08f9-d448-5407-9aad-5290dd7ab264"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestSetExtensions = "98d24dd4-01ad-11ea-1b02-c9a08f80db04"

[compat]
FLoops = "0.1"
CUDA = "3"
FoldsCUDA = "0.1"
ImageMorphology = "0.2, 0.3"
Images = "0.24, 0.25"
TestSetExtensions = "2.0"
julia = "1.6"

[publish]
title = "DistanceTransforms.jl"
