[deps]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DistanceTransforms = "71182807-4d06-4237-8dd0-bdafe4d097e2"
DistanceTransformsPy = "d85f584c-7717-483c-8218-10621e78a8b8"
HTMLStrings = "c47fe496-5789-4377-b1db-55e89f2ee0c6"
ImageMorphology = "787d08f9-d448-5407-9aad-5290dd7ab264"
ImageSegmentation = "80713f31-8817-5129-9cf8-209ff8fb23e1"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Losers = "1785af8d-d312-496e-9b53-daf6ddaba92c"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"
oneAPI = "8f75cd03-7ff8-4ecb-9b8f-daf728133b1b"
